config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'

    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :quests do
      resources :answers, except: %i[new show]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end
  end
end

app/models/quest.rb
# frozen_string_literal: true

class Quest < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true, length: { minimum: 5 }
end

app/controllers/quests_controller.rb
# frozen_string_literal: true

class QuestsController < ApplicationController
  before_action :set_quest!, only: %i[edit update destroy show]

  def index
    @quests = Quest.order(created_at: :desc).page(params[:page]).decorate
  end

  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new quest_params
    if @quest.save
      flash[:success] = t '.success'
      redirect_to quests_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @quest.update quest_params
      flash[:success] = t '.success'
      redirect_to quests_path
    else
      render :edit
    end
  end

  def destroy
    @quest.destroy # if ????
    flash[:success] = t '.success'
    redirect_to quests_path
  end

  def show
    @answer = @quest.answers.build
    @answers = @quest.answers.order(created_at: :desc).page(params[:page])
    @answers = @answers.decorate
  end

  private

  def set_quest!
    @quest = Quest.find(params[:id]).decorate
  end

  def quest_params
    params.require(:quest).permit(:title, :body)
  end
end

app/views/quests/_buttons.html.erb
<div>
  <%= link_to "Show", quest_path(quest), class: 'btn btn-primary' %>  
  <%= link_to "Edit", edit_quest_path(quest), class: 'btn btn-secondary'  %> 
  <%= link_to "Delete", quest_path(quest), class: 'btn btn-danger', data: {
                        turbo_method: :delete, 
                        turbo_confirm: "Are you sure?" } %> 
</div>

app/views/quests/_form.html.erb
<%= render "shared/errors", object: @quest %>

<%= form_with model: @quest, data: { turbo: false } do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control', 
                        placeholder: "Title" %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control',
                      placeholder: "Text" %>
    </div>
  </div>

  <%= f.submit "Submit question", class: "btn btn-primary" %>
<% end %>

app/views/quests/edit.html.erb
<%= provide :page_title, "Edit question" %>
<% currently_at "Questions" %>

<h1 class="mb-4">Edit question</h1>

<%= render "form" %>

app/views/quests/index.html.erb
<%= provide :page_title, "Questions" %>
<% currently_at "Questions" %>

<h1 class="mb-4">Questions</h1>

<%= paginate @quests %>

<% @quests.each do |quest| %>
  <article class="card my-3">
    <div class="card-body">
      <h2><%= quest.title %></h2>

      <section class="card-text"> 
        <time datetime = <%= quest.formatted_created_at %>>
          <%= quest.formatted_created_at %>
        </time>

        <p class="my-2">
          <%= truncate strip_tags(quest.body), length: 150 %>
        </p>
      </section>

      <%= render 'buttons', quest: quest %>
    </div>  
  </article> 
<% end %>

<%= paginate @quests %>

app/views/quests/new.html.erb
<%= provide :page_title, "Create new question" %>
<% currently_at "Create question" %>

<h1 class="mb-4">Create new question</h1>

<%= render "form"%>

app/views/quests/show.html.erb
<%= provide :page_title, @quest.title %>
<% currently_at "Questions" %>

<h1 class="mb-4"><%= @quest.title %></h1>

<time datetime = <%= @quest.formatted_created_at %>>
  <%= @quest.formatted_created_at %>
</time>
<div class="lead my-3">
  <%= sanitize @quest.body %>
</div>

<%= render 'quests/buttons', quest: @quest %>

<h3 class="my-4">Write your answer</h3>

<%= render "answers/form" %>

<h2 class='mt-4'>Answers</h2>

<%= paginate @answers %> 

<%= render @answers %>

<%= paginate @answers %> 