config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'

    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :quests do
      resources :answers, except: %i[new show]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end
  end
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <% object.errors.full_messages.each do |error| %>
    <div class="alert alert-danger">
      <%= error %>
    </div>
  <% end %>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class='p-3 bg-dark text-white'>
    <div class='container'>
      <nav class='d-flex flex-wrap align-items-center justify-content-center'>
        <ul class='nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center md-md-0'>
          <li><%= nav_tab t('menu.home'), root_path, class: 'nav-link px-2',
                          current_page: current_page %></li>
          <li><%= nav_tab "Questions", quests_path, class: 'nav-link px-2',
                          current_page: current_page %></li>
          <li><%= nav_tab "Create question", new_quest_path, class: 'nav-link px-2',
                          current_page: current_page %></li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 md-md-0"><!--  add dropdown -->
          <% I18n.available_locales.each do |locale| %>
            <li class="my-2 text-white">
              <%= link_to t(locale), root_path(locale: locale),
                          class: 'nav-link px-2 text-white' %>
            </li>
          <% end %>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 md-md-0">
          <% if user_signed_in? %>
            <li class="dropdown"> <!--  add dropdown -->
              <%= nav_tab current_user.name_or_email, '#', 
                          class: 'nav-link px-2',
                          current_page: current_page %>
            </li>
            <li>
              <%= nav_tab 'Edit profile', edit_user_path(current_user), 
                          class: 'nav-link px-2',
                          current_page: current_page %>
            </li>
            <li>
              <%= link_to 'Log out', session_path, class: 'nav-link px-2',
                          data: { turbo_method: :delete } %>
            </li>
          <% else %>
            <li><%= nav_tab "Sign Up", new_user_path, class: 'nav-link px-2',
                          current_page: current_page %></li>
            <li><%= nav_tab "Log In", new_session_path, class: 'nav-link px-2',
                          current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>