config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#index'

    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :quests do
      resources :answers, except: %i[new show]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :quest

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_quest!
  before_action :set_answer!, except: :create

  def create
    @answer = @quest.answers.build answer_params
    if @answer.save
      flash[:success] = 'Answer created'
      redirect_to quest_path(@quest)
    else
      @quest = @quest.decorate
      @answers = @quest.answers.order(created_at: :desc).page(params[:page])
      @answers = @answers.decorate
      render 'quests/show'
    end
  end

  def destroy
    @answer.destroy
    # binding.break
    flash[:success] = 'Answer deleted!'
    redirect_to quest_path(@quest), status: :see_other
  end

  def edit; end

  def update
    if @answer.update answer_params
      flash[:success] = 'Answer updated!'
      redirect_to quest_path(@quest, anchor: dom_id(@answer))
      # redirect_to quest_path(@quest)
      # сначала отправляется, а потом в урле чистится якорь, разобраться
    else
      render :edit
    end
  end

  private

  def set_quest!
    @quest = Quest.find params[:quest_id]
  end

  def set_answer!
    @answer = @quest.answers.find params[:id]
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.erb
<%= tag.article class: "mb-3 card", id: dom_id(answer) do  %>
  <div class="card-body">
    <div class="card-text">
      <small><time datetime = <%= answer.formatted_created_at %>>
        <%= answer.formatted_created_at %>
      </time></small>

      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </div>
    <%= link_to "Edit", edit_quest_answer_path(@quest, answer), class: 'btn btn-info' %>
    <%= link_to "Delete", quest_answer_path(@quest, answer), class: 'btn btn-danger', data: {
                          turbo_method: :delete, 
                          turbo_confirm: "Are you sure?" } %> 
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= render "shared/errors", object: @answer %>

<%= form_with model: [@quest, @answer], data: { turbo: false } do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control',
                      placeholder: "Text" %>
    </div>
  </div>

  <%= f.submit "Submit answer", class: "btn btn-primary" %>
<% end %>

app/views/answers/edit.html.erb
<%= provide :page_title, "Edit answer" %>
<% currently_at "Questions" %>

<h1 class="mb-4">Edit answer</h1>

<%= render "form" %>